```yaml
name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose Terraform action"
        required: true
        type: choice
        default: apply
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:

      # Checkout Repository
      - name: Checkout
        uses: actions/checkout@v4


      # Configure AWS using GitHub OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::364410975057:role/oidc
          aws-region: eu-north-1
          role-session-name: GitHubActions


      # Verify AWS Authentication
      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity


      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      # Terraform Init
      # Uses backend.tf and S3 state
      - name: Terraform Init
        run: |
          terraform init


      # Terraform Validate
      - name: Terraform Validate
        run: |
          terraform validate


      # Terraform Plan
      - name: Terraform Plan
        if: inputs.action == 'apply'
        env:
          TF_VAR_aws_region: eu-north-1
          TF_VAR_availability_zone: eu-north-1a
          TF_VAR_ami_id: ami-0734cbe7f841a2e9b
          TF_VAR_key_name: alpkey
          TF_VAR_allowed_ssh_cidr: 49.37.134.2/32
        run: |
          terraform plan


      # Terraform Apply
      - name: Terraform Apply
        if: inputs.action == 'apply'
        env:
          TF_VAR_aws_region: eu-north-1
          TF_VAR_availability_zone: eu-north-1a
          TF_VAR_ami_id: ami-0734cbe7f841a2e9b
          TF_VAR_key_name: alpkey
          TF_VAR_allowed_ssh_cidr: 49.37.134.2/32
        run: |
          terraform apply -auto-approve


      # Terraform Destroy
      - name: Terraform Destroy
        if: inputs.action == 'destroy'
        env:
          TF_VAR_aws_region: eu-north-1
          TF_VAR_availability_zone: eu-north-1a
          TF_VAR_ami_id: ami-0734cbe7f841a2e9b
          TF_VAR_key_name: alpkey
          TF_VAR_allowed_ssh_cidr: 49.37.134.2/32
        run: |
          terraform destroy -auto-approve
```
