
name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose Terraform action"
        required: true
        type: choice
        default: apply
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::364410975057:role/oidc
          aws-region: eu-north-1
          role-session-name: GitHubActions

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Validate
        run: |
          terraform validate

      - name: Terraform Plan
        if: inputs.action == 'apply'
        run: |
          terraform plan

      - name: Terraform Apply
        if: inputs.action == 'apply'
        run: |
          terraform apply -auto-approve

      - name: Terraform Destroy
        if: inputs.action == 'destroy'
        run: |
          terraform destroy -auto-approve

